version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.<your-region>.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t seleniumjs-nodejs .
      - docker tag seleniumjs-nodejs:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/seleniumjs:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/seleniumjs:latest

artifacts:
  files:
    - '**/*'